apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomoto
  labels:
    app: zomoto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomoto
  template:
    metadata:
      labels:
        app: zomoto
    spec:
      containers:
      - name: zomoto
        image: manikantaprasanna/zomoto
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
